config {
    type: "incremental", 
    schema: "dataform_mart", 
    name: "dim_track", 
    uniqueKey: ["track_sk"], 
    description: "Dim track table storages track's metadata"
}

SELECT 
    ${utils.generate_sk("track_uri")} AS track_sk, 
    track_uri, 
    track_name, 
    album_name, 
    ${utils.get_updated_time()} AS updated_at, 
    ${utils.get_batch_id()} AS dwh_batch_id, 
    '${dataform.projectConfig.vars.source_name}' AS source_system
FROM ${ref("stg_track")}
