config {
  type: "view",
  schema: "dataform_staging_validation",
  name: "stg_track_validation",
  tags: ["staging", "validation"],
}

SELECT
  *,
  CASE
    WHEN track_uri IS NULL
    OR track_uri = "" THEN "track_uri is null or empty"
    WHEN track_name IS NULL
    OR track_name = "" THEN "track_name is null or empty"
    ELSE "valid"
  END
    AS validation_status
FROM
  ${ref("stg_spotify_track_reference")}